model:
  name: noise_split_net

img_basic_info:
  img_height: 128
  img_width: 128
  img_channels: 3

TTA:
  enabled: true
  n_augmentations: 5

train:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  lr_step_size: 20
  lr_gamma: 0.5

test:
  batch_size: 32
  shuffle: false

dev:
  batch_size: 32
  shuffle: false